definitions:
  app.SoftwarePkgBasicInfoDTO:
    properties:
      applied_at:
        type: string
      id:
        type: string
      importer:
        type: string
      phase:
        type: string
      pkg_name:
        type: string
      repo_link:
        type: string
    type: object
  app.SoftwarePkgsDTO:
    properties:
      pkgs:
        items:
          $ref: '#/definitions/app.SoftwarePkgBasicInfoDTO'
        type: array
      total:
        type: integer
    type: object
  controller.ResponseData:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  controller.softwarePkgRequest:
    properties:
      package_desc:
        type: string
      package_name:
        type: string
      package_platform:
        type: string
      package_reason:
        type: string
      package_sig:
        type: string
      source_code_license:
        type: string
      source_code_url:
        type: string
    required:
    - package_desc
    - package_name
    - package_platform
    - package_reason
    - package_sig
    - source_code_license
    - source_code_url
    type: object
info:
  contact: {}
paths:
  /v1/softwarepkg:
    get:
      consumes:
      - application/json
      description: list software packages
      parameters:
      - description: importer of the softwarePkg
        in: query
        name: importer
        type: string
      - description: phase of the softwarePkg
        in: query
        name: phase
        type: string
      - description: count per page
        in: query
        name: count_per_page
        type: integer
      - description: page num which starts from 1
        in: query
        name: page_num
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.SoftwarePkgsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: list software packages
      tags:
      - SoftwarePkg
    post:
      consumes:
      - application/json
      description: apply a new software package
      parameters:
      - description: body of applying a new software package
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controller.softwarePkgRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: apply a new software package
      tags:
      - SoftwarePkg
swagger: "2.0"
