definitions:
  controller.ResponseData:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  controller.softwareRequest:
    properties:
      package_desc:
        type: string
      package_name:
        type: string
      package_platform:
        type: string
      package_reason:
        type: string
      package_sig:
        type: string
      source_code_license:
        type: string
      source_code_url:
        type: string
      username:
        type: string
    required:
    - package_desc
    - package_name
    - package_platform
    - package_reason
    - package_sig
    - source_code_license
    - source_code_url
    - username
    type: object
info:
  contact: {}
paths:
  /v1/add-software:
    post:
      consumes:
      - application/json
      description: add software
      parameters:
      - description: body of creating software pkg
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controller.softwareRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: add software
      tags:
      - softwarePkg
swagger: "2.0"
